version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    volumes:
      - ./gateway:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - backend

  user:
    build: ./user
    container_name: user
    volumes:
      - ./user:/usr/src/app
    networks:
      - backend
  
  user_db:
    image: postgres:latest
    container_name: user_db
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_database
    volumes:
      - ./user_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

networks:
  backend:
    driver: bridge

volumes:
  user_db:
